services:
  
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant
    env_file:
      - .env

  crewai-wrapper:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - qdrant
    env_file:
      - .env
  

volumes:
  openwebui_data:
  qdrant_data: