research_task:
  description: >
    Conduct exhaustive research on {topic} for {current_year}, ensuring at least
    12 high-quality, independent sources and flagging any controversial findings.
  expected_output: >
    Markdown list of 10-12 ranked insights, each with inline numeric citations
    and a final "Self-Check" block (see agent guidelines).
  agent: researcher

reporting_task:
  description: >
    Expand the validated insight list into a full executive report following the
    outline and style rules in the analyst's backstory.
  expected_output: >
    Markdown report with H1/H2 structure, figures placeholders, and bibliography.
    Every citation must include the source URL.
  agent: reporting_analyst